name: nicocesar
favicon: null
layout_spectrum: 0.3254132515285164
typography_spectrum: 0.21371903223916888
title: Nico Cesar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.363762462278828
  lightness: 0.5483315703459084
  saturation: 0.39234155509620905
  rhythmicContrast: 0.932595893740654
purpose: []
